disabled_rules:
  - opening_brace
  - line_length

excluded:
  - SnapTests
  - Carthage

file_length:
  warning: 200
  error: 400

trailing_whitespace:
  ignores_empty_lines: true
  
reporter: "xcode"